language: android
sudo: required
jdk: oraclejdk8

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_install:
- yes | sdkmanager "platforms;android-27"
- git clone https://github.com/MD2Korg/mCerebrum-API-android.git /home/travis/build/MD2Korg/mCerebrum-API-android
env:
  - TEST_DIR=libraries/phonesensor
  - TEST_DIR=libraries/cerebralcortex
  - TEST_DIR=libraries/datakit
  - TEST_DIR=libraries/samsungwatch
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-android-support
    - extra-google-m2repository
  - extra-android-m2repository

script:
- cd @TEST_DIR && "./gradlew assembleRelease"
